In [2]:
using PythonCall

pd = pyimport("pandas")
plt = pyimport("matplotlib.pyplot")
ticker = pyimport("matplotlib.ticker")

df = pd.read_csv("C:\\Users\\Thinkpad\\dataset\\tweets.csv", index_col=nothing, encoding="ISO-8859-1")

df

Python:
         Target  ...                                               Text
0             0  ...  is upset that he can't update his Facebook by ...
1             0  ...  @Kenichan I dived many times for the ball. Man...
2             0  ...    my whole body feels itchy and like its on fire
3             0  ...  @nationwideclass no, it's not behaving at all....
4             0  ...                      @Kwesidei not the whole crew
...         ...  ...                                                ...
1048570       4  ...           My GrandMa is making Dinenr with my Mum
1048571       4  ...  Mid-morning snack time... A bowl of cheese noo...
1048572       4  ...  @ShaDeLa same here  say it like from the Termi...
1048573       4  ...             @DestinyHope92 im great thaanks  wbuu?
1048574       4  ...               cant wait til her date this weekend

[1048575 rows x 6 columns]

In [3]:
grouped = df.groupby("Target")
#.apply(x -> x.sample(n=200, random_state=42))
df_sample = pd.concat([group.sample(n=200, random_state=42) for (name, group) in grouped])
df_sample.reset_index()

Python:
      index  ...                                               Text
0    212188  ...      @dickiemaxx  Win a few; lose  few  a  with a
1    299036  ...  @lavjonas tokio hotel and won tokio hotel that...
2    475977  ...  Right, off to work  Only 5 hours to go until I...
3    385829  ...  @daibarnes and guess who's landed that plum jo...
4    138859  ...  @rabbit_rabid can't sleep... come give me hug...
..      ...  ...                                                ...
395  982156  ...  @joolzgirl haha! I understand, you can try it ...
396  943638  ...                              Doing Work As Always
397  852098  ...                                    SO DON'T DO IT
398  993849  ...  schooool; last full weekkk!  and then amandas ...
399  997906  ...  @OtakUniverse Moshi, Moshi!  My Brute is getti...

[400 rows x 7 columns]

In [4]:
df_sample["Date"] = pd.to_datetime(df_sample["Date"], format = "%a %b %d %H:%M:%S PDT %Y")
df_sample["Month"] = df_sample["Date"].dt.month
ax = df_sample["Month"].value_counts().sort_index().plot(
    kind="bar", 
    title = "comments per month", 
    color = "blue", 
    figsize = (10, 5))
ax.set_xlabel("Months")
#plt.show()

Python: Text(0.5, 0, 'Months')

In [5]:
most_frequens_perMonth = df_sample.groupby("Target")["Month"].value_counts().unstack(fill_value = 0)
minor_locator = ticker.AutoMinorLocator(10)
ax = plt.figure(figsize=(10, 5)).add_subplot(111)
most_frequens_perMonth.plot(
    kind="bar",
    title = "comments per month", 
    xlabel = "Target",
    ylabel = "Number of comments",
    legend = true,
    
).grid(
    linestyle = "--",
    color = "grey",
    axis = "both",
    which = "both"
)
ax.yaxis.set_minor_locator(minor_locator)
plt.xticks(rotation = 0)
#plt.show()

Python: (array([0, 1]), [Text(0, 0, '0'), Text(1, 0, '4')])

In [6]:
most_frequens_perMonth

Python:
Month    4    5    6
Target
0       11   49  140
4       47  153    0

In [7]:

df_sample["Text"] = map(x -> strip(lowercase(replace(string(x), r"(@\w+|\d+|[^\w\s])"=> ""))), df_sample["Text"])
df_filtered = df_sample.filter(["Target", "Text"], axis=1)

Python:
        Target                                               Text
212188       0                     win a few lose  few  a  with a
299036       0          tokio hotel and won tokio hotel thats bad
475977       0  right off to work  only  hours to go until im ...
385829       0  and guess whos landed that plum job moi  were ...
138859       0                        cant sleep come give me hug
...        ...                                                ...
982156       4  haha i understand you can try it anytime you w...
943638       4                               doing work as always
852098       4                                      so dont do it
993849       4  schooool last full weekkk  and then amandas to...
997906       4  moshi moshi  my brute is getting stronger read...

[400 rows x 2 columns]

In [8]:
nltk = pyimport("nltk")

nltk.download("stopwords")
nltk.download("punkt")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Thinkpad\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Thinkpad\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Thinkpad\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

Python: True

In [9]:
stopwords = nltk.corpus.stopwords.words("english")
lemmatize = nltk.stem.WordNetLemmatizer()


function word_proccess(text) 

    tokens = nltk.word_tokenize(text)
    filtered_tokens = [lemmatize.lemmatize(token) for token in tokens if !(token in stopwords)]
    return filtered_tokens
    
end

df_filtered["Tokens"] = map(word_proccess, df_sample.Text)
df_filtered

Python:
        Target  ...                                             Tokens
212188       0  ...                                        [win, lose]
299036       0  ...           [tokio, hotel, tokio, hotel, thats, bad]
475977       0  ...              [right, work, hour, go, im, free, xd]
385829       0  ...  [guess, who, landed, plum, job, moi, hosting, ...
138859       0  ...                     [cant, sleep, come, give, hug]
...        ...  ...                                                ...
982156       4  ...  [haha, understand, try, anytime, want, looking...
943638       4  ...                                     [work, always]
852098       4  ...                                             [dont]
993849       4  ...  [schooool, last, full, weekkk, amandas, study,...
997906       4  ...  [moshi, moshi, brute, getting, stronger, ready...

[400 rows x 3 columns]

In [10]:
sklearn = pyimport("sklearn")
gensim = pyimport("gensim")
np = pyimport("numpy")

Python: <module 'numpy' from 'C:\\Users\\Thinkpad\\.julia\\environments\\v1.11\\.CondaPkg\\env\\Lib\\site-packages\\numpy\\__init__.py'>

In [ ]:
model = gensim.models.Word2Vec(sentences = df_filtered["Tokens"], vector_size=100, window= 5, min_count=1, workers=4)

function text_to_vector(tokens, model)
    vectors = [np.copy(model.wv[token]) for token in tokens if haskey(model.wv, token)]
    return return length(vectors) > 0 ? np.mean(vectors, axis=0) : np.zeros(model.vector_size)
end

sentence_vectors = [text_to_vector(tokens, model) for tokens in df_filtered["Tokens"]]
sentence_vectors_df = np.array(sentence_vectors)
df_filtered["sentence_vector"] = sentence_vectors_df

vector = np.array(df_filtered["sentence_vector"].tolist()).copy()
y = np.array(df_filtered["Target"]).copy()

train_test_split = sklearn.model_selection.train_test_split

X_train, X_test, y_train, y_test = train_test_split(vector, y, test_size=0.4, random_state=42)

In [24]:
svm = sklearn.svm.SVC()
GridSearchCV = sklearn.model_selection.GridSearchCV

param = Dict(
    "C" => [0.1, 1, 10],
    "kernel" => ["linear", "rbf"],
    "gamma" => ["scale", "auto"]
)

params = PythonCall.pydict(param)

gridsearch = GridSearchCV(svm, params, cv=5, scoring="accuracy", error_score = "raise")
gridsearch.fit(X_train, y_train)

Python:
GridSearchCV(cv=5, error_score='raise', estimator=SVC(),
             param_grid={'C': Julia:
3-element Vector{Float64}:
  0.1
  1.0
 10.0,
                         'gamma': Julia:
2-element Vector{String}:
 "scale"
 "auto",
                         'kernel': Julia:
2-element Vector{String}:
 "linear"
 "rbf"},
             scoring='accuracy')

In [25]:
println("Best parameters: ", gridsearch.best_params_)
println("Best score: ", gridsearch.best_score_)
y_pred = gridsearch.predict(X_test)
accuracy = sklearn.metrics.accuracy_score(y_test, y_pred)

results = pd.DataFrame(gridsearch.cv_results_)
display(results)

Python:
    mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0        0.001629      0.000816  ...        0.006250                3
1        0.000000      0.000000  ...        0.006250                3
2        0.004358      0.005735  ...        0.006250                3
3        0.003632      0.003196  ...        0.006250                3
4        0.003197      0.004671  ...        0.006250                3
5        0.003594      0.007189  ...        0.055551                1
6        0.002813      0.003788  ...        0.006250                3
7        0.001400      0.001200  ...        0.006250                3
8        0.000800      0.000980  ...        0.006250                3
9        0.002403      0.003206  ...        0.066291                2
10       0.001400      0.000489  ...        0.006250                3
11       0.000881      0.001087  ...        0.006250                3

[12 rows x 16 columns]

Best parameters: {'C': 1.0, 'gamma': 'scale', 'kernel': 'rbf'}
Best score: 0.584375